### ISSUE TITLE
Fails serialization of dict/HashmapE with one element

### ISSUE THREAD

**Issue by neodix42** [neodix42/ton4j#2]
```
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
at org.ton.java.cell.TonHashMap.flatten(TonHashMap.java:144)
at org.ton.java.cell.TonHashMapE.serialize(TonHashMapE.java:37)
```

**Comment by neodix42** [comment]
Fixed with release 0.2.0

**Comment by neodix42** [comment]
closed by mistake, the issue still exists

**Comment by neodix42** [comment]
with version 0.4.9
